# Site settings
baseurl = "http://jrclarkin.com/"
languageCode = "en-us"
title = "Jonathan Clarkin"
theme = "hugo-custom-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Jonathan Clarkin"
	description = "Software Craftsman, building and discovering tools and techniques to help teams, and teaching others of his findings."


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Jonathan Clarkin"
		shortBio = "BUILD // LEARN // SHARE"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About me"
		bio = "**Jonathan specializes in learning and building** for software teams. He is a full stack developer with a passion for agile teams that are looking to empower customers and users."

		[[params.about.skills]]
			name = "Learning"
			value = 10

		[[params.about.skills]]
			name = "Teaching"
			value = 8

		[[params.about.skills]]
			name = "Communication"
			value = 7

		[[params.about.skills]]
			name = "Visual Design"
			value = 5

		[[params.about.skills]]
			name = "UX Design"
			value = 6

		[[params.about.skills]]
			name = "Programming"
			value = 7

	# Work section
	[params.work]
		title = "Work"

		[[params.work.projects]]
			name = "Nivaha Restore"
			folder = "nivaha-restore"

		[[params.work.projects]]
			name = "CAST Conference"
			folder = "cast-2015"

		[[params.work.projects]]
			name = "KWSQA Workshop"
			folder = "kwsqa-2015"

		[[params.work.projects]]
			name = "Mxi API & DSL"
			folder = "mxi-api"

		[[params.work.projects]]
			name = "Mxi Mobile Prototype"
			folder = "mxi-mobile"

		[[params.work.projects]]
			name = "Mxi Hackathons"
			folder = "mxi-hackathons"

		[[params.work.projects]]
			name = "Mxi Core Automation"
			folder = "mxi-automation"

		[[params.work.projects]]
			name = "Mxi Team Leadership"
			folder = "mxi-team-lead"


	# Clients section
	[params.clients]
		title = "Peers"

		[[params.clients.list]]
			avatar = "face-mhynie.jpg"
			name   = "Martin Hynie"
			title  = "Spiritual Warrior of Testing, Mxi Technologies"
			quote  = "**Jonathan helped us implement creative** and maintainable automation frameworks in support of our team missions. More importantly, Jonathan proved to be an incredible facilitator of continuous learning and sharing."
			logo   = "logo-mxi.png"

		[[params.clients.list]]
			avatar = "face-rhalliday.jpg"
			name   = "Russ Halliday"
			title  = "CEO & Co-Founder, Nivaha"
			quote  = ""
			logo   = "logo-nivaha.png"

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "linkedin"
			link = "//www.linkedin.com/in/jonathanclarkin"

		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/_jrwc"

		[[params.contact.social]]
			icon = "github"
			link = "//www.github.com/jclarkin"

	# Blog secion
	[params.blog]
		title = "Blog"
		total = 1

	[params.footer]
		# copyright = "Published under the Unlicense License."
